# Generated by Django 6.1.1 on 2026-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_product_category_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('skincare', 'Skincare'), ('makeup', 'Makeup'), ('haircare', 'Haircare'), ('fragrance', 'Fragrance')], max_length=20),
        ),
    ]
